### ISSUE TITLE
Client secret is expired

### ISSUE THREAD

**Issue by qdraw** [zumwald/stateless-vsts-oauth#12]
Hi I've got this error. I think the clientSecret on the application is expired

When I go to this url:

```
https://stateless-vsts-oauth.azurewebsites.net/oauth-callback?code=<<REDACTED>>&state=<<GUID>>
```
you will see this:
```
{
  "Error": "invalid_request",
  "ErrorDescription": "Client secret is expired."
}
```

**Comment by beatzball** [comment]
the maintainer is no longer at MSFT, but i reached out to see if there's someone else that might be able to update the resource

**Comment by zumwald** [comment]
I'm on vacation without access to a laptop to resolve this. The ADO portal to manage applications doesn't work on mobile, even with some attempts to spoof a desktop browser. 

I'll look into this once I'm home. ETA for next response is by 21-Nov.

**Comment by zumwald** [comment]
After spending some time fighting with the VSTS marketplace portal I can't find a way to actually renew/add a new client secret for vsts apps. I will likely create a new app (that'll be good for another 5yr) and push a rev of the client with the updated clientId.

**Comment by zumwald** [comment]
Fixed. It's using a new VSTS app registration now so you'll have to reconsent the app. Default ClientId is updated in https://www.npmjs.com/package/better-vsts-npm-auth/v/7.0.0 so upgrading via `npm i -g better-vsts-npm-auth@latest` to get that change.

**Comment by cretumarius** [comment]
For me it's still not working the v7.0.0. I receive 
<img width="1722" alt="image" src="https://user-images.githubusercontent.com/64973825/203013260-eb207908-ef88-415e-9268-1a89e385a358.png">

**Comment by qdraw** [comment]
@cretumarius you should update the `.vstsnpmauthrc` file here is the token in specified

**Comment by cretumarius** [comment]
@qdraw thanks for help but I am not sure what to update in `.vstsnpmauthrc`. Can you provide more details? Thanks in advance!

**Comment by qdraw** [comment]
@cretumarius see: https://github.com/zumwald/better-vsts-npm-auth/blob/main/lib/config.test.ts and https://github.com/zumwald/better-vsts-npm-auth/blob/main/lib/config.ts for the default values. The clientId should match in your `$HOME/.vstsnpmauthrc` file. The `refresh_token` is unvalid since the clientId is changed

**Comment by cretumarius** [comment]
@qdraw Thank you, it works now!
